%YAML:1.0
show_debug_info: false
#if true will recompute the covariance matrixes from the input images
train: false

#path of the input images used to compute covariance matrixes
input_path: RGBD_Face_dataset_training/biwi/
#output path where cropped faces will be saved if show_debug_info is set to true
output_path: Results/Training/
#output path where the covariance matrixes are saved
save_path: Save/Train/

#number of persons for this training
number_of_persons: 5
number_of_photo_per_person: 15
number_of_poses: 1
starting_person: 1
starting_photo: 0

#if true will move the used images in samefolder/used/...
move_used_images: true

#if true will try to detected automatically the pose of the person using the face pose estimation
automatic_pose_detection: false
